using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreePair.Core.Bbp;
using FreePair.Core.SwissSys;
using FreePair.Core.Tournaments;

namespace FreePair.Core.Tests.Tournaments;

/// <summary>
/// Tests for the TD pre-commit intervention mutations:
/// <list type="bullet">
///   <item><see cref="TournamentMutations.SwapPairingColors"/> — feature #4</item>
///   <item><see cref="TournamentMutations.SwapBoardOpponents"/> — feature #6</item>
///   <item><see cref="TournamentMutations.ConvertPairingToHalfPointBye"/> — feature #8</item>
/// </list>
/// Each mutation operates on an un-played round (typically the round
/// just generated by <see cref="TournamentMutations.AppendRound"/>) and
/// updates both the <see cref="Round"/> and the relevant players'
/// <see cref="Player.History"/> entries so standings / wall chart
/// stay consistent.
/// </summary>
public class TdInterventionMutationsTests
{
    private const string SampleFileName = "Chess_A2Z_April_Open_2026_SwissSys11.sjson";

    private static async Task<Tournament> LoadAsync()
    {
        var importer = new SwissSysImporter();
        var raw = await importer.ImportAsync(TestPaths.SwissSysSample(SampleFileName));
        return SwissSysMapper.Map(raw);
    }

    /// <summary>Appends a fake round 4 to Open I so we have an un-played round to poke at.</summary>
    private static async Task<Tournament> LoadWithUnplayedRound4Async()
    {
        var t = await LoadAsync();
        var bbp = new BbpPairingResult(
            new[]
            {
                new BbpPairing(1, 2), new BbpPairing(3, 4), new BbpPairing(5, 6),
                new BbpPairing(7, 8), new BbpPairing(9, 10), new BbpPairing(11, 12),
                new BbpPairing(13, 14), new BbpPairing(15, 16),
            },
            Array.Empty<int>());
        return TournamentMutations.AppendRound(t, "Open I", bbp);
    }

    // ============ #4 SwapPairingColors ============

    [Fact]
    public async Task SwapPairingColors_swaps_white_and_black_and_flips_history()
    {
        var t = await LoadWithUnplayedRound4Async();

        t = TournamentMutations.SwapPairingColors(t, "Open I",
            round: 4, whitePair: 1, blackPair: 2);

        var section = t.Sections.Single(s => s.Name == "Open I");
        var r4 = section.Rounds.Single(r => r.Number == 4);
        var board = r4.Pairings.Single(p => (p.WhitePair == 2 && p.BlackPair == 1)
                                         || (p.WhitePair == 1 && p.BlackPair == 2));
        Assert.Equal(2, board.WhitePair);
        Assert.Equal(1, board.BlackPair);

        // History colours flipped for both players.
        var p1 = section.Players.Single(p => p.PairNumber == 1);
        var p2 = section.Players.Single(p => p.PairNumber == 2);
        Assert.Equal(PlayerColor.Black, p1.History[3].Color);
        Assert.Equal(PlayerColor.White, p2.History[3].Color);
    }

    [Fact]
    public async Task SwapPairingColors_throws_on_scored_pairing()
    {
        var t = await LoadAsync();
        // Round 1 of Open I is scored.
        Assert.Throws<InvalidOperationException>(() =>
            TournamentMutations.SwapPairingColors(t, "Open I",
                round: 1, whitePair: 9, blackPair: 1));
    }

    [Fact]
    public async Task SwapPairingColors_throws_when_pairing_missing()
    {
        var t = await LoadWithUnplayedRound4Async();
        Assert.Throws<InvalidOperationException>(() =>
            TournamentMutations.SwapPairingColors(t, "Open I",
                round: 4, whitePair: 99, blackPair: 100));
    }

    // ============ #6 SwapBoardOpponents ============

    [Fact]
    public void SwapBoardOpponents_swaps_blacks_and_preserves_colours()
    {
        // Build a fresh section with 4 players and no prior history
        // so the rematch guard never fires for the first round.
        var players = Enumerable.Range(1, 4)
            .Select(i => new Player(
                PairNumber: i,
                Name: $"P{i}",
                UscfId: null,
                Rating: 1600 - i,
                SecondaryRating: null,
                MembershipExpiration: null,
                Club: null,
                State: null,
                Team: null,
                RequestedByeRounds: Array.Empty<int>(),
                History: Array.Empty<FreePair.Core.SwissSys.RoundResult>()))
            .ToArray();

        var section = new Section(
            Name: "S",
            Title: null,
            Kind: SectionKind.Swiss,
            TimeControl: null,
            RoundsPaired: 0,
            RoundsPlayed: 0,
            FinalRound: 3,
            FirstBoard: 1,
            Players: players,
            Teams: Array.Empty<Team>(),
            Rounds: Array.Empty<Round>(),
            Prizes: new Prizes(Array.Empty<Prize>(), Array.Empty<Prize>()));

        var t = new Tournament(
            Title: "T",
            StartDate: null,
            EndDate: null,
            TimeControl: null,
            NachEventId: null,
            Sections: new[] { section });

        // Round 1: board 1 = 1w vs 2b, board 2 = 3w vs 4b.
        var bbp = new BbpPairingResult(
            new[] { new BbpPairing(1, 2), new BbpPairing(3, 4) },
            Array.Empty<int>());
        t = TournamentMutations.AppendRound(t, "S", bbp);

        // Swap → board 1: 1w vs 4b, board 2: 3w vs 2b.
        t = TournamentMutations.SwapBoardOpponents(t, "S",
            round: 1, boardA: 1, boardB: 2);

        var s = t.Sections.Single();
        var r1 = s.Rounds.Single();

        var b1 = r1.Pairings.Single(p => p.Board == 1);
        var b2 = r1.Pairings.Single(p => p.Board == 2);
        Assert.Equal(1, b1.WhitePair);
        Assert.Equal(4, b1.BlackPair);
        Assert.Equal(3, b2.WhitePair);
        Assert.Equal(2, b2.BlackPair);

        var p1 = s.Players.Single(p => p.PairNumber == 1);
        var p4 = s.Players.Single(p => p.PairNumber == 4);
        Assert.Equal(4, p1.History[0].Opponent);
        Assert.Equal(1, p4.History[0].Opponent);
    }

    [Fact]
    public async Task SwapBoardOpponents_rejects_swap_that_would_recreate_previous_pairing()
    {
        var t = await LoadWithUnplayedRound4Async();
        // In Open I round 2, pair 1 already played pair 4 (white). So
        // swapping boards 1 (1 vs 2) and 2 (3 vs 4) would recreate
        // 1 vs 4 and must be rejected.
        Assert.Throws<InvalidOperationException>(() =>
            TournamentMutations.SwapBoardOpponents(t, "Open I",
                round: 4, boardA: 1, boardB: 2));
    }

    [Fact]
    public async Task SwapBoardOpponents_throws_on_scored_pairing()
    {
        var t = await LoadAsync();
        // Round 1 is scored.
        Assert.Throws<InvalidOperationException>(() =>
            TournamentMutations.SwapBoardOpponents(t, "Open I",
                round: 1, boardA: 1, boardB: 2));
    }

    [Fact]
    public async Task SwapBoardOpponents_rejects_same_board_arguments()
    {
        var t = await LoadWithUnplayedRound4Async();
        Assert.Throws<ArgumentException>(() =>
            TournamentMutations.SwapBoardOpponents(t, "Open I",
                round: 4, boardA: 1, boardB: 1));
    }

    // ============ #8 ConvertPairingToHalfPointBye ============

    [Fact]
    public async Task ConvertPairingToHalfPointBye_gives_half_to_target_and_full_to_opponent()
    {
        var t = await LoadWithUnplayedRound4Async();

        // Pair #2 asks for late ½-pt bye; pair #1 was their opponent.
        t = TournamentMutations.ConvertPairingToHalfPointBye(t, "Open I",
            round: 4, halfByePair: 2);

        var section = t.Sections.Single(s => s.Name == "Open I");
        var r4 = section.Rounds.Single(r => r.Number == 4);

        // Pairing removed.
        Assert.DoesNotContain(r4.Pairings, p =>
            (p.WhitePair == 1 && p.BlackPair == 2) ||
            (p.WhitePair == 2 && p.BlackPair == 1));

        // Two new byes in place.
        Assert.Contains(r4.Byes, b => b.PlayerPair == 2 && b.Kind == ByeKind.Half);
        Assert.Contains(r4.Byes, b => b.PlayerPair == 1 && b.Kind == ByeKind.Full);

        var p1 = section.Players.Single(p => p.PairNumber == 1);
        var p2 = section.Players.Single(p => p.PairNumber == 2);
        Assert.Equal(RoundResultKind.FullPointBye, p1.History[3].Kind);
        Assert.Equal(1m, p1.History[3].Score);
        Assert.Equal(RoundResultKind.HalfPointBye, p2.History[3].Kind);
        Assert.Equal(0.5m, p2.History[3].Score);
    }

    [Fact]
    public async Task ConvertPairingToHalfPointBye_throws_when_player_not_in_any_pairing()
    {
        var t = await LoadWithUnplayedRound4Async();
        Assert.Throws<InvalidOperationException>(() =>
            TournamentMutations.ConvertPairingToHalfPointBye(t, "Open I",
                round: 4, halfByePair: 999));
    }

    [Fact]
    public async Task ConvertPairingToHalfPointBye_throws_on_scored_pairing()
    {
        var t = await LoadAsync();
        Assert.Throws<InvalidOperationException>(() =>
            TournamentMutations.ConvertPairingToHalfPointBye(t, "Open I",
                round: 1, halfByePair: 1));
    }
}
